import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type LanguageCode = 'en' | 'sv' | 'de' | 'es' | 'tr';

export const LANGUAGES: Array<{ code: LanguageCode; label: string; short: string }> = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'sv', label: 'Svenska', short: 'SV' },
  { code: 'de', label: 'Deutsch', short: 'DE' },
  { code: 'es', label: 'Español', short: 'ES' },
  { code: 'tr', label: 'Türkçe', short: 'TR' }
];

const en = {
  language: 'Language',
  brandSubtitle: 'Save & Manage AI Prompts',
  gallery: 'Gallery',
  favorites: 'Favorites',
  myPrompts: 'My Prompts',
  exportTitle: 'Export collection as JSON',
  importTitle: 'Import collection from JSON',
  becomeAuthor: 'Become an Author',
  saveNewPrompt: 'Save New Prompt',
  saveShort: 'Save',
  importSuccess: 'Collection imported successfully!',
  importError: 'Could not import. Make sure the file is valid JSON.',
  heroBadge: 'Welcome to your secret AI vault',
  heroTitleLine1: 'Unlock & Save Your',
  heroTitleLine2: 'Secret AI Prompts',
  heroDescription: 'Welcome to SecretPrompts. Build your personal library of exclusive prompts with matching reference images. Discover templates, edit in real time and copy with one click.',
  searchPlaceholder: 'Search prompts, styles, tags or AI models...',
  clear: 'Clear',
  featureImageTitle: 'Save with Image',
  featureImageText: 'Visual library',
  featureCopyTitle: '1-Click Copy',
  featureCopyText: 'Ready for AI',
  featureVariablesTitle: 'Smart Variables',
  featureVariablesText: 'Fill templates',
  featureModelsTitle: 'Multiple Models',
  featureModelsText: 'Midjourney, DALL-E',
  manageCategories: 'Categories',
  manageCategoriesTitle: 'Manage categories',
  adminLoginTitle: 'Log in as Admin',
  logoutAdmin: 'Log Out',
  logoutAdminTitle: 'Log out from Admin',
  model: 'Model:',
  allModels: 'All Models',
  tag: 'Tag:',
  allTags: 'All Tags',
  resetFilters: 'Reset filters',
  showing: 'Showing',
  prompts: 'prompts',
  sortNewest: 'Newest first',
  sortOldest: 'Oldest first',
  sortTitle: 'Title A-Z',
  sortPopular: 'Most viewed',
  sortLikes: 'Most liked',
  authorBadge: 'Author Program',
  authorTitle: 'Become an Author on',
  authorDescription: 'Share your best AI prompts with the community and help others create stronger images, copy and workflows. Send a short application and it lands directly in the SecretPrompts inbox.',
  authorPointEmail: 'Application is sent to {email}',
  authorPointCreators: 'Made for creators, prompt engineers and AI designers',
  authorPointPortfolio: 'Portfolio is optional but helps during review',
  authorFormTitle: 'Author Application',
  authorFormSubtitle: 'Fill in the form below. We will send it securely to the SecretPrompts inbox.',
  displayName: 'Display Name',
  displayNamePlaceholder: 'Your author name',
  displayNameHelp: 'This name will appear on your published prompts.',
  contactEmail: 'Contact Email',
  contactEmailPlaceholder: 'you@example.com',
  contactEmailHelp: 'Used only to reply to your application.',
  portfolioUrl: 'Portfolio URL',
  optional: 'optional',
  portfolioPlaceholder: 'https://your-portfolio.com',
  portfolioHelp: 'Share your work to help us review your application.',
  experienceLabel: 'Experience with AI Prompts',
  experiencePlaceholder: 'Tell us about your experience with AI tools and prompts...',
  motivationLabel: 'Why do you want to become an author?',
  motivationPlaceholder: 'Share your motivation for joining our author community...',
  authorRequiredError: 'Fill in all required fields before submitting your application.',
  authorSuccess: 'Thank you! Your application has been sent to {email}.',
  authorAutoError: 'Automatic sending failed. Your email app opens as backup.',
  authorMailFallback: 'Or open in your email app',
  authorSubmit: 'Submit Application',
  authorSending: 'Sending Application...',
  authorClose: 'Close Author Application',
  authorFirestoreSuccess: 'Application submitted! Admin will review it.',
  authorFirestoreError: 'Something went wrong. Please try again later.',
  adminPanelTitle: 'Admin Panel',
  adminPendingAuthorAppsTitle: '{count} pending Become an Author application(s)',
  adminPendingAuthorAppsBanner: '{count} new Become an Author application(s) — click to review',
  adminReviewApplications: 'Review',
  adminAuthorAppsLoadError: 'Could not load author applications. Check Firestore rules for the applications collection.',
  adminViewProfile: 'View profile',
  adminSendWarning: 'Send warning',
  adminBroadcastTitle: 'Message all registered users',
  adminBroadcastHint: 'Sends a warning message every user must accept or reject.',
  adminBroadcastPlaceholder: 'Write your message to all users...',
  adminBroadcastSend: 'Send to all',
  adminBroadcastSending: 'Sending...',
  adminBroadcastSuccess: 'Message sent to {count} users.',
  adminBroadcastError: 'Could not send message. Try again.',
  authorExampleImage: 'Example image',
  authorExampleImageHint: 'Upload an example of your prompt work (required)',
  authorImageUploading: 'Uploading image...',
  authorImageRequired: 'Please upload an example image.',
  authorImageUploadError: 'Image upload failed. Try another file.',
  authorLoginButton: 'Log in',
  authorLoginRequired: 'Log in to apply',
  authorLoginRequiredHint: 'Author applications are tied to your account — one application per month.',
  authorMonthlyLimit: 'Registered accounts: max one application per 30 days.',
  authorPointExampleImage: 'Example image required with your application',
  authorCooldownTitle: 'You cannot apply right now',
  authorCooldownUntil: 'Next application available: {date}',
  authorCooldownError: 'You must wait before submitting a new application.',
  authorPendingReview: 'You already have an application under review.',
  warningModalTitle: 'Message from Admin',
  warningModalSubtitle: 'Please read and confirm or decline',
  warningAccept: 'I accept',
  warningReject: 'I do not accept',
  warningYouAccepted: 'You accepted this message',
  warningYouRejected: 'You declined this message',
  warningReplyLabel: 'Your reply to Admin (optional)',
  warningReplyPlaceholder: 'Write a short message back (max 500 characters)...',
  warningReplyCharCount: '{current} / {max}',
  warningYourReply: 'Your reply',
  warningUserReply: 'User reply',
  categoryAll: 'All',
  categoryPortrait: 'Portraits',
  categoryLandscape: 'Landscape & Nature',
  categoryArchitecture: 'Architecture',
  categoryLogos: 'Logos & Icons',
  categoryFantasy: 'Fantasy & Sci-Fi',
  categoryWeb: 'Web & UI',
  category3d: '3D & Anime',
  categorySport: 'Sports',
  categoryDigitalArt: 'Digital Art',
  categoryIllustration: 'Illustration',
  categoryConceptArt: 'Concept Art',
  categoryFood: 'Food & Drink',
  categoryFashion: 'Fashion & Clothing',
  categoryProductDesign: 'Product Design',
  categoryAbstract: 'Abstract',
  categoryCyberpunk: 'Cyberpunk',
  categorySteampunk: 'Steampunk'
};

type TranslationKey = string;

const translations: Record<LanguageCode, Record<TranslationKey, string>> = {
  en,
  sv: {
    language: 'Språk',
    brandSubtitle: 'Created By nRn World',
    gallery: 'Galleriet',
    favorites: 'Favoriter',
    myPrompts: 'Mina Prompter',
    exportTitle: 'Exportera samling som JSON',
    importTitle: 'Importera samling från JSON',
    becomeAuthor: 'Bli Författare',
    saveNewPrompt: 'Spara Ny Prompt',
    saveShort: 'Spara',
    importSuccess: 'Samlingen har importerats framgångsrikt!',
    importError: 'Kunde inte importera. Kontrollera att filen är korrekt JSON.',
    heroBadge: 'Välkommen till ditt hemliga AI-valv',
    heroTitleLine1: 'Lås upp & Spara Dina',
    heroTitleLine2: 'Hemliga AI-Prompter',
    heroDescription: 'Välkommen till SecretPrompts. Skapa ditt personliga bibliotek av exklusiva prompter med tillhörande referensbilder. Upptäck mallar, redigera i realtid och kopiera med ett enda klick.',
    searchPlaceholder: 'Sök bland prompter, stilar, taggar eller AI-modeller...',
    clear: 'Rensa',
    featureImageTitle: 'Spara med Bild',
    featureImageText: 'Visuellt bibliotek',
    featureCopyTitle: '1-Klick Kopiering',
    featureCopyText: 'Redo för AI',
    featureVariablesTitle: 'Smarta Variabler',
    featureVariablesText: 'Fyll i mallar',
    featureModelsTitle: 'Flera Modeller',
    featureModelsText: 'Midjourney, DALL-E',
    manageCategories: 'Kategorier',
    manageCategoriesTitle: 'Hantera kategorier',
    adminLoginTitle: 'Logga in som Admin',
    logoutAdmin: 'Logga Ut',
    logoutAdminTitle: 'Logga ut från Admin',
    model: 'Modell:',
    allModels: 'Alla Modeller',
    tag: 'Tagg:',
    allTags: 'Alla Taggar',
    resetFilters: 'Återställ filter',
    showing: 'Visar',
    prompts: 'prompter',
    sortNewest: 'Nyast först',
    sortOldest: 'Äldst först',
    sortTitle: 'Titel A-Ö',
    sortPopular: 'Mest populärt',
    sortLikes: 'Flest gilla',
    authorBadge: 'Author Program',
    authorTitle: 'Bli Författare på',
    authorDescription: 'Dela dina bästa AI-prompter med communityn och hjälp andra skapa starkare bilder, texter och workflows. Skicka in en kort ansökan så hamnar den direkt hos SecretPrompts-teamet.',
    authorPointEmail: 'Ansökan skickas till {email}',
    authorPointCreators: 'Passar kreatörer, prompt engineers och AI-designers',
    authorPointPortfolio: 'Portfolio är valfritt men hjälper vid granskning',
    authorFormTitle: 'Author Application',
    authorFormSubtitle: 'Fyll i formuläret nedan. Vi skickar det säkert till SecretPrompts inbox.',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Your author name',
    displayNameHelp: 'This name will appear on your published prompts.',
    contactEmail: 'Contact Email',
    contactEmailPlaceholder: 'you@example.com',
    contactEmailHelp: 'Used only to reply to your application.',
    portfolioUrl: 'Portfolio URL',
    optional: 'optional',
    portfolioPlaceholder: 'https://your-portfolio.com',
    portfolioHelp: 'Share your work to help us review your application.',
    experienceLabel: 'Experience with AI Prompts',
    experiencePlaceholder: 'Tell us about your experience with AI tools and prompts...',
    motivationLabel: 'Why do you want to become an author?',
    motivationPlaceholder: 'Share your motivation for joining our author community...',
    authorRequiredError: 'Fyll i alla obligatoriska fält innan du skickar ansökan.',
    authorSuccess: 'Tack! Din ansökan har skickats till {email}.',
    authorAutoError: 'Automatisk skickning misslyckades. Din e-postapp öppnas som backup.',
    authorMailFallback: 'Eller öppna i e-postappen',
    authorSubmit: 'Submit Application',
    authorSending: 'Sending Application...',
    authorClose: 'Stäng Author Application',
    authorFirestoreSuccess: 'Ansökan skickad! Admin kommer att granska den.',
    authorFirestoreError: 'Något gick fel. Försök igen senare.',
    adminPanelTitle: 'Adminpanel',
    adminPendingAuthorAppsTitle: '{count} väntande Become an Author-ansökning(ar)',
    adminPendingAuthorAppsBanner: '{count} ny(a) Become an Author-ansökan/ansökningar — klicka för att granska',
    adminReviewApplications: 'Granska',
    adminAuthorAppsLoadError: 'Kunde inte ladda författaransökningar. Kontrollera Firestore-regler för samlingen applications.',
    adminViewProfile: 'Visa profil',
    adminSendWarning: 'Skicka varning',
    adminBroadcastTitle: 'Meddelande till alla registrerade',
    adminBroadcastHint: 'Skickar ett meddelande som varje användare måste godkänna eller avvisa.',
    adminBroadcastPlaceholder: 'Skriv meddelande till alla användare...',
    adminBroadcastSend: 'Skicka till alla',
    adminBroadcastSending: 'Skickar...',
    adminBroadcastSuccess: 'Meddelande skickat till {count} användare.',
    adminBroadcastError: 'Kunde inte skicka meddelande. Försök igen.',
    authorExampleImage: 'Exempelbild',
    authorExampleImageHint: 'Ladda upp ett exempel på ditt prompt-arbete (obligatoriskt)',
    authorImageUploading: 'Laddar upp bild...',
    authorImageRequired: 'Ladda upp en exempelbild.',
    authorImageUploadError: 'Bilduppladdning misslyckades. Prova en annan fil.',
    authorLoginButton: 'Logga in',
    authorLoginRequired: 'Logga in för att ansöka',
    authorLoginRequiredHint: 'Author-ansökningar kopplas till ditt konto — max en ansökan per månad.',
    authorMonthlyLimit: 'Registrerade konton: max en ansökan per 30 dagar.',
    authorPointExampleImage: 'Exempelbild krävs med ansökan',
    authorCooldownTitle: 'Du kan inte ansöka just nu',
    authorCooldownUntil: 'Nästa ansökan möjlig: {date}',
    authorCooldownError: 'Du måste vänta innan du skickar en ny ansökan.',
    authorPendingReview: 'Du har redan en ansökan som granskas.',
    warningModalTitle: 'Meddelande från Admin',
    warningModalSubtitle: 'Läs och godkänn eller avvisa',
    warningAccept: 'Jag godkänner',
    warningReject: 'Jag godkänner inte',
    warningYouAccepted: 'Du godkände meddelandet',
    warningYouRejected: 'Du godkände inte meddelandet',
    warningReplyLabel: 'Ditt svar till Admin (valfritt)',
    warningReplyPlaceholder: 'Skriv ett kort meddelande tillbaka (max 500 tecken)...',
    warningReplyCharCount: '{current} / {max}',
    warningYourReply: 'Ditt svar',
    warningUserReply: 'Användarens svar',
    categoryAll: 'Alla',
    categoryPortrait: 'Porträtt',
    categoryLandscape: 'Landskap & Natur',
    categoryArchitecture: 'Arkitektur',
    categoryLogos: 'Logotyper & Ikoner',
    categoryFantasy: 'Fantasy & Sci-Fi',
    categoryWeb: 'Webb & UI',
    category3d: '3D & Anime',
    categorySport: 'Sport',
    categoryDigitalArt: 'Digital Art',
    categoryIllustration: 'Illustration',
    categoryConceptArt: 'Konceptkonst',
    categoryFood: 'Mat & Dryck',
    categoryFashion: 'Mode & Kläder',
    categoryProductDesign: 'Produktdesign',
    categoryAbstract: 'Abstrakt',
    categoryCyberpunk: 'Cyberpunk',
    categorySteampunk: 'Steampunk'
  },
  de: {
    language: 'Sprache',
    brandSubtitle: 'KI-Prompts speichern & verwalten',
    gallery: 'Galerie',
    favorites: 'Favoriten',
    myPrompts: 'Meine Prompts',
    exportTitle: 'Sammlung als JSON exportieren',
    importTitle: 'Sammlung aus JSON importieren',
    becomeAuthor: 'Autor werden',
    saveNewPrompt: 'Neuen Prompt speichern',
    saveShort: 'Speichern',
    importSuccess: 'Sammlung erfolgreich importiert!',
    importError: 'Import fehlgeschlagen. Prüfe, ob die Datei gültiges JSON ist.',
    heroBadge: 'Willkommen in deinem geheimen KI-Tresor',
    heroTitleLine1: 'Entsperre & speichere deine',
    heroTitleLine2: 'geheimen KI-Prompts',
    heroDescription: 'Willkommen bei SecretPrompts. Baue deine persönliche Bibliothek exklusiver Prompts mit passenden Referenzbildern. Entdecke Vorlagen, bearbeite live und kopiere mit einem Klick.',
    searchPlaceholder: 'Prompts, Stile, Tags oder KI-Modelle suchen...',
    clear: 'Leeren',
    featureImageTitle: 'Mit Bild speichern',
    featureImageText: 'Visuelle Bibliothek',
    featureCopyTitle: '1-Klick-Kopie',
    featureCopyText: 'Bereit für KI',
    featureVariablesTitle: 'Smarte Variablen',
    featureVariablesText: 'Vorlagen ausfüllen',
    featureModelsTitle: 'Mehrere Modelle',
    featureModelsText: 'Midjourney, DALL-E',
    manageCategories: 'Kategorien',
    manageCategoriesTitle: 'Kategorien verwalten',
    adminLoginTitle: 'Als Admin einloggen',
    logoutAdmin: 'Abmelden',
    logoutAdminTitle: 'Admin abmelden',
    model: 'Modell:',
    allModels: 'Alle Modelle',
    tag: 'Tag:',
    allTags: 'Alle Tags',
    resetFilters: 'Filter zurücksetzen',
    showing: 'Zeigt',
    prompts: 'Prompts',
    sortNewest: 'Neueste zuerst',
    sortOldest: 'Älteste zuerst',
    sortTitle: 'Titel A-Z',
    sortPopular: 'Meist gesehen',
    sortLikes: 'Meiste Likes',
    authorBadge: 'Autorenprogramm',
    authorTitle: 'Autor werden bei',
    authorDescription: 'Teile deine besten KI-Prompts mit der Community und hilf anderen, bessere Bilder, Texte und Workflows zu erstellen. Sende eine kurze Bewerbung direkt an das SecretPrompts-Team.',
    authorPointEmail: 'Bewerbung wird an {email} gesendet',
    authorPointCreators: 'Für Kreative, Prompt Engineers und KI-Designer',
    authorPointPortfolio: 'Portfolio ist optional, hilft aber bei der Prüfung',
    authorFormTitle: 'Autorenbewerbung',
    authorFormSubtitle: 'Fülle das Formular unten aus. Wir senden es sicher an den SecretPrompts-Posteingang.',
    displayName: 'Anzeigename',
    displayNamePlaceholder: 'Dein Autorenname',
    displayNameHelp: 'Dieser Name erscheint auf deinen veröffentlichten Prompts.',
    contactEmail: 'Kontakt-E-Mail',
    contactEmailPlaceholder: 'du@example.com',
    contactEmailHelp: 'Wird nur für die Antwort auf deine Bewerbung genutzt.',
    portfolioUrl: 'Portfolio-URL',
    optional: 'optional',
    portfolioPlaceholder: 'https://dein-portfolio.com',
    portfolioHelp: 'Teile deine Arbeiten, damit wir deine Bewerbung prüfen können.',
    experienceLabel: 'Erfahrung mit KI-Prompts',
    experiencePlaceholder: 'Erzähle uns von deiner Erfahrung mit KI-Tools und Prompts...',
    motivationLabel: 'Warum möchtest du Autor werden?',
    motivationPlaceholder: 'Teile deine Motivation für unsere Autoren-Community...',
    authorRequiredError: 'Fülle bitte alle Pflichtfelder aus, bevor du die Bewerbung sendest.',
    authorSuccess: 'Danke! Deine Bewerbung wurde an {email} gesendet.',
    authorAutoError: 'Automatisches Senden fehlgeschlagen. Deine E-Mail-App wird als Backup geöffnet.',
    authorMailFallback: 'Oder in deiner E-Mail-App öffnen',
    authorSubmit: 'Bewerbung senden',
    authorSending: 'Bewerbung wird gesendet...',
    authorClose: 'Autorenbewerbung schließen',
    authorFirestoreSuccess: 'Bewerbung eingereicht! Admin wird sie prüfen.',
    authorFirestoreError: 'Etwas ist schief gelaufen. Bitte versuche es später erneut.',
    adminPanelTitle: 'Admin-Panel',
    adminPendingAuthorAppsTitle: '{count} ausstehende Become-an-Author-Bewerbung(en)',
    adminPendingAuthorAppsBanner: '{count} neue Become-an-Author-Bewerbung(en) — zum Prüfen klicken',
    adminReviewApplications: 'Prüfen',
    adminAuthorAppsLoadError: 'Autorenbewerbungen konnten nicht geladen werden. Firestore-Regeln für applications prüfen.',
    adminViewProfile: 'Profil ansehen',
    adminSendWarning: 'Warnung senden',
    adminBroadcastTitle: 'Nachricht an alle registrierten Nutzer',
    adminBroadcastHint: 'Jeder Nutzer muss die Nachricht annehmen oder ablehnen.',
    adminBroadcastPlaceholder: 'Nachricht an alle schreiben...',
    adminBroadcastSend: 'An alle senden',
    adminBroadcastSending: 'Senden...',
    adminBroadcastSuccess: 'Nachricht an {count} Nutzer gesendet.',
    adminBroadcastError: 'Senden fehlgeschlagen.',
    authorExampleImage: 'Beispielbild',
    authorExampleImageHint: 'Beispiel hochladen (Pflicht)',
    authorImageUploading: 'Bild wird hochgeladen...',
    authorImageRequired: 'Bitte Beispielbild hochladen.',
    authorImageUploadError: 'Upload fehlgeschlagen.',
    authorLoginButton: 'Einloggen',
    authorLoginRequired: 'Zum Bewerben einloggen',
    authorLoginRequiredHint: 'Eine Bewerbung pro Monat pro Konto.',
    authorMonthlyLimit: 'Max. eine Bewerbung alle 30 Tage.',
    authorPointExampleImage: 'Beispielbild erforderlich',
    authorCooldownTitle: 'Bewerbung derzeit nicht möglich',
    authorCooldownUntil: 'Nächste Bewerbung: {date}',
    authorCooldownError: 'Bitte warten vor neuer Bewerbung.',
    authorPendingReview: 'Bewerbung wird bereits geprüft.',
    warningModalTitle: 'Nachricht vom Admin',
    warningModalSubtitle: 'Bitte bestätigen oder ablehnen',
    warningAccept: 'Ich akzeptiere',
    warningReject: 'Ich lehne ab',
    warningYouAccepted: 'Du hast akzeptiert',
    warningYouRejected: 'Du hast abgelehnt',
    warningReplyLabel: 'Deine Antwort an Admin (optional)',
    warningReplyPlaceholder: 'Kurze Nachricht (max. 500 Zeichen)...',
    warningReplyCharCount: '{current} / {max}',
    warningYourReply: 'Deine Antwort',
    warningUserReply: 'Nutzerantwort',
    categoryAll: 'Alle',
    categoryPortrait: 'Porträts',
    categoryLandscape: 'Landschaft & Natur',
    categoryArchitecture: 'Architektur',
    categoryLogos: 'Logos & Icons',
    categoryFantasy: 'Fantasy & Sci-Fi',
    categoryWeb: 'Web & UI',
    category3d: '3D & Anime',
    categorySport: 'Sport',
    categoryDigitalArt: 'Digitale Kunst',
    categoryIllustration: 'Illustration',
    categoryConceptArt: 'Konzeptkunst',
    categoryFood: 'Essen & Trinken',
    categoryFashion: 'Mode & Kleidung',
    categoryProductDesign: 'Produktdesign',
    categoryAbstract: 'Abstrakt',
    categoryCyberpunk: 'Cyberpunk',
    categorySteampunk: 'Steampunk'
  },
  es: {
    language: 'Idioma',
    brandSubtitle: 'Guarda y gestiona prompts de IA',
    gallery: 'Galería',
    favorites: 'Favoritos',
    myPrompts: 'Mis Prompts',
    exportTitle: 'Exportar colección como JSON',
    importTitle: 'Importar colección desde JSON',
    becomeAuthor: 'Ser Autor',
    saveNewPrompt: 'Guardar Nuevo Prompt',
    saveShort: 'Guardar',
    importSuccess: 'Colección importada correctamente.',
    importError: 'No se pudo importar. Asegúrate de que el archivo sea JSON válido.',
    heroBadge: 'Bienvenido a tu bóveda secreta de IA',
    heroTitleLine1: 'Desbloquea y guarda tus',
    heroTitleLine2: 'prompts secretos de IA',
    heroDescription: 'Bienvenido a SecretPrompts. Crea tu biblioteca personal de prompts exclusivos con imágenes de referencia. Descubre plantillas, edita en tiempo real y copia con un clic.',
    searchPlaceholder: 'Buscar prompts, estilos, etiquetas o modelos de IA...',
    clear: 'Limpiar',
    featureImageTitle: 'Guardar con Imagen',
    featureImageText: 'Biblioteca visual',
    featureCopyTitle: 'Copia en 1 clic',
    featureCopyText: 'Listo para IA',
    featureVariablesTitle: 'Variables inteligentes',
    featureVariablesText: 'Rellena plantillas',
    featureModelsTitle: 'Varios modelos',
    featureModelsText: 'Midjourney, DALL-E',
    manageCategories: 'Categorías',
    manageCategoriesTitle: 'Gestionar categorías',
    adminLoginTitle: 'Iniciar sesión como Admin',
    logoutAdmin: 'Cerrar Sesión',
    logoutAdminTitle: 'Cerrar sesión de Admin',
    model: 'Modelo:',
    allModels: 'Todos los modelos',
    tag: 'Etiqueta:',
    allTags: 'Todas las etiquetas',
    resetFilters: 'Restablecer filtros',
    showing: 'Mostrando',
    prompts: 'prompts',
    sortNewest: 'Más recientes',
    sortOldest: 'Más antiguos',
    sortTitle: 'Título A-Z',
    sortPopular: 'Más visto',
    sortLikes: 'Más gustado',
    authorBadge: 'Programa de Autores',
    authorTitle: 'Ser Autor en',
    authorDescription: 'Comparte tus mejores prompts de IA con la comunidad y ayuda a otros a crear mejores imágenes, textos y workflows. Envía una solicitud breve directamente al equipo de SecretPrompts.',
    authorPointEmail: 'La solicitud se envía a {email}',
    authorPointCreators: 'Para creadores, prompt engineers y diseñadores de IA',
    authorPointPortfolio: 'El portfolio es opcional, pero ayuda en la revisión',
    authorFormTitle: 'Solicitud de Autor',
    authorFormSubtitle: 'Completa el formulario. Lo enviaremos de forma segura a la bandeja de SecretPrompts.',
    displayName: 'Nombre público',
    displayNamePlaceholder: 'Tu nombre de autor',
    displayNameHelp: 'Este nombre aparecerá en tus prompts publicados.',
    contactEmail: 'Correo de contacto',
    contactEmailPlaceholder: 'tu@example.com',
    contactEmailHelp: 'Solo se usa para responder tu solicitud.',
    portfolioUrl: 'URL del portfolio',
    optional: 'opcional',
    portfolioPlaceholder: 'https://tu-portfolio.com',
    portfolioHelp: 'Comparte tu trabajo para ayudarnos a revisar tu solicitud.',
    experienceLabel: 'Experiencia con prompts de IA',
    experiencePlaceholder: 'Cuéntanos tu experiencia con herramientas y prompts de IA...',
    motivationLabel: '¿Por qué quieres ser autor?',
    motivationPlaceholder: 'Comparte tu motivación para unirte a nuestra comunidad...',
    authorRequiredError: 'Completa todos los campos obligatorios antes de enviar la solicitud.',
    authorSuccess: 'Gracias. Tu solicitud se ha enviado a {email}.',
    authorAutoError: 'Falló el envío automático. Se abrirá tu app de correo como respaldo.',
    authorMailFallback: 'O abrir en tu app de correo',
    authorSubmit: 'Enviar solicitud',
    authorSending: 'Enviando solicitud...',
    authorClose: 'Cerrar solicitud de autor',
    authorFirestoreSuccess: 'Solicitud enviada. El administrador la revisará.',
    authorFirestoreError: 'Algo salió mal. Inténtalo de nuevo más tarde.',
    adminPanelTitle: 'Panel de Admin',
    adminPendingAuthorAppsTitle: '{count} solicitud(es) Become an Author pendiente(s)',
    adminPendingAuthorAppsBanner: '{count} nueva(s) solicitud(es) Become an Author — clic para revisar',
    adminReviewApplications: 'Revisar',
    adminAuthorAppsLoadError: 'No se pudieron cargar las solicitudes. Revisa las reglas de Firestore para applications.',
    adminViewProfile: 'Ver perfil',
    adminSendWarning: 'Enviar aviso',
    adminBroadcastTitle: 'Mensaje a todos los registrados',
    adminBroadcastHint: 'Cada usuario debe aceptar o rechazar el mensaje.',
    adminBroadcastPlaceholder: 'Escribe el mensaje...',
    adminBroadcastSend: 'Enviar a todos',
    adminBroadcastSending: 'Enviando...',
    adminBroadcastSuccess: 'Enviado a {count} usuarios.',
    adminBroadcastError: 'No se pudo enviar.',
    authorExampleImage: 'Imagen de ejemplo',
    authorExampleImageHint: 'Sube un ejemplo (obligatorio)',
    authorImageUploading: 'Subiendo...',
    authorImageRequired: 'Sube una imagen de ejemplo.',
    authorImageUploadError: 'Error al subir.',
    authorLoginButton: 'Iniciar sesión',
    authorLoginRequired: 'Inicia sesión para solicitar',
    authorLoginRequiredHint: 'Una solicitud por mes por cuenta.',
    authorMonthlyLimit: 'Máx. una solicitud cada 30 días.',
    authorPointExampleImage: 'Imagen de ejemplo obligatoria',
    authorCooldownTitle: 'No puedes solicitar ahora',
    authorCooldownUntil: 'Próxima solicitud: {date}',
    authorCooldownError: 'Debes esperar antes de una nueva solicitud.',
    authorPendingReview: 'Ya tienes una solicitud en revisión.',
    warningModalTitle: 'Mensaje del Admin',
    warningModalSubtitle: 'Lee y acepta o rechaza',
    warningAccept: 'Acepto',
    warningReject: 'No acepto',
    warningYouAccepted: 'Aceptaste el mensaje',
    warningYouRejected: 'Rechazaste el mensaje',
    warningReplyLabel: 'Tu respuesta al Admin (opcional)',
    warningReplyPlaceholder: 'Escribe un mensaje breve (máx. 500 caracteres)...',
    warningReplyCharCount: '{current} / {max}',
    warningYourReply: 'Tu respuesta',
    warningUserReply: 'Respuesta del usuario',
    categoryAll: 'Todo',
    categoryPortrait: 'Retratos',
    categoryLandscape: 'Paisaje y Naturaleza',
    categoryArchitecture: 'Arquitectura',
    categoryLogos: 'Logos e Iconos',
    categoryFantasy: 'Fantasía y Sci-Fi',
    categoryWeb: 'Web y UI',
    category3d: '3D y Anime',
    categorySport: 'Deportes',
    categoryDigitalArt: 'Arte Digital',
    categoryIllustration: 'Ilustración',
    categoryConceptArt: 'Arte Conceptual',
    categoryFood: 'Comida & Bebida',
    categoryFashion: 'Moda & Ropa',
    categoryProductDesign: 'Diseño de Producto',
    categoryAbstract: 'Abstracto',
    categoryCyberpunk: 'Cyberpunk',
    categorySteampunk: 'Steampunk'
  },
  tr: {
    language: 'Dil',
    brandSubtitle: 'AI Promptlarını Kaydet ve Yönet',
    gallery: 'Galeri',
    favorites: 'Favoriler',
    myPrompts: 'Promptlarım',
    exportTitle: 'Koleksiyonu JSON olarak dışa aktar',
    importTitle: 'Koleksiyonu JSON dosyasından içe aktar',
    becomeAuthor: 'Yazar Ol',
    saveNewPrompt: 'Yeni Prompt Kaydet',
    saveShort: 'Kaydet',
    importSuccess: 'Koleksiyon başarıyla içe aktarıldı.',
    importError: 'İçe aktarılamadı. Dosyanın geçerli JSON olduğundan emin ol.',
    heroBadge: 'Gizli AI kasana hoş geldin',
    heroTitleLine1: 'Gizli AI promptlarını',
    heroTitleLine2: 'aç ve kaydet',
    heroDescription: 'SecretPrompts’a hoş geldin. Referans görsellerle birlikte özel promptlardan oluşan kişisel kütüphaneni oluştur. Şablonları keşfet, canlı düzenle ve tek tıkla kopyala.',
    searchPlaceholder: 'Prompt, stil, etiket veya AI modeli ara...',
    clear: 'Temizle',
    featureImageTitle: 'Görselle Kaydet',
    featureImageText: 'Görsel kütüphane',
    featureCopyTitle: 'Tek Tıkla Kopyala',
    featureCopyText: 'AI için hazır',
    featureVariablesTitle: 'Akıllı Değişkenler',
    featureVariablesText: 'Şablonları doldur',
    featureModelsTitle: 'Birden Fazla Model',
    featureModelsText: 'Midjourney, DALL-E',
    manageCategories: 'Kategoriler',
    manageCategoriesTitle: 'Kategorileri yönet',
    adminLoginTitle: 'Admin olarak giriş yap',
    logoutAdmin: 'Çıkış Yap',
    logoutAdminTitle: 'Admin çıkışı yap',
    model: 'Model:',
    allModels: 'Tüm Modeller',
    tag: 'Etiket:',
    allTags: 'Tüm Etiketler',
    resetFilters: 'Filtreleri sıfırla',
    showing: 'Gösterilen',
    prompts: 'prompt',
    sortNewest: 'Önce en yeni',
    sortOldest: 'Önce en eski',
    sortTitle: 'Başlık A-Z',
    sortPopular: 'En çok izlenen',
    sortLikes: 'En çok beğeni',
    authorBadge: 'Yazar Programı',
    authorTitle: 'Yazar Ol:',
    authorDescription: 'En iyi AI promptlarını toplulukla paylaş ve başkalarının daha güçlü görseller, metinler ve workflowlar oluşturmasına yardım et. Kısa başvurun doğrudan SecretPrompts ekibine ulaşır.',
    authorPointEmail: 'Başvuru {email} adresine gönderilir',
    authorPointCreators: 'İçerik üreticiler, prompt mühendisleri ve AI tasarımcıları için',
    authorPointPortfolio: 'Portfolyo isteğe bağlıdır ama incelemede yardımcı olur',
    authorFormTitle: 'Yazar Başvurusu',
    authorFormSubtitle: 'Aşağıdaki formu doldur. SecretPrompts gelen kutusuna güvenli şekilde göndeririz.',
    displayName: 'Görünen İsim',
    displayNamePlaceholder: 'Yazar adın',
    displayNameHelp: 'Bu isim yayınlanan promptlarında görünür.',
    contactEmail: 'İletişim E-postası',
    contactEmailPlaceholder: 'sen@example.com',
    contactEmailHelp: 'Sadece başvuruna cevap vermek için kullanılır.',
    portfolioUrl: 'Portfolyo URL',
    optional: 'isteğe bağlı',
    portfolioPlaceholder: 'https://portfolyon.com',
    portfolioHelp: 'Başvurunu incelememize yardımcı olması için çalışmalarını paylaş.',
    experienceLabel: 'AI Prompt Deneyimi',
    experiencePlaceholder: 'AI araçları ve promptlarla deneyimini anlat...',
    motivationLabel: 'Neden yazar olmak istiyorsun?',
    motivationPlaceholder: 'Yazar topluluğumuza katılma motivasyonunu paylaş...',
    authorRequiredError: 'Başvuruyu göndermeden önce tüm zorunlu alanları doldur.',
    authorSuccess: 'Teşekkürler! Başvurun {email} adresine gönderildi.',
    authorAutoError: 'Otomatik gönderim başarısız oldu. Yedek olarak e-posta uygulaman açılır.',
    authorMailFallback: 'Veya e-posta uygulamanda aç',
    authorSubmit: 'Başvuruyu Gönder',
    authorSending: 'Başvuru gönderiliyor...',
    authorClose: 'Yazar başvurusunu kapat',
    authorFirestoreSuccess: 'Başvuru gönderildi! Admin inceleyecek.',
    authorFirestoreError: 'Bir şeyler yanlış gitti. Lütfen daha sonra tekrar dene.',
    adminPanelTitle: 'Admin Paneli',
    adminPendingAuthorAppsTitle: '{count} bekleyen Become an Author başvurusu',
    adminPendingAuthorAppsBanner: '{count} yeni Become an Author başvurusu — incelemek için tıkla',
    adminReviewApplications: 'İncele',
    adminAuthorAppsLoadError: 'Yazar başvuruları yüklenemedi. applications koleksiyonu için Firestore kurallarını kontrol edin.',
    adminViewProfile: 'Profili görüntüle',
    adminSendWarning: 'Uyarı gönder',
    adminBroadcastTitle: 'Tüm kayıtlı kullanıcılara mesaj',
    adminBroadcastHint: 'Her kullanıcı mesajı kabul veya reddetmelidir.',
    adminBroadcastPlaceholder: 'Tüm kullanıcılara mesaj yaz...',
    adminBroadcastSend: 'Herkese gönder',
    adminBroadcastSending: 'Gönderiliyor...',
    adminBroadcastSuccess: '{count} kullanıcıya gönderildi.',
    adminBroadcastError: 'Gönderilemedi.',
    authorExampleImage: 'Örnek görsel',
    authorExampleImageHint: 'Örnek yükle (zorunlu)',
    authorImageUploading: 'Yükleniyor...',
    authorImageRequired: 'Lütfen örnek görsel yükleyin.',
    authorImageUploadError: 'Yükleme başarısız.',
    authorLoginButton: 'Giriş yap',
    authorLoginRequired: 'Başvurmak için giriş yapın',
    authorLoginRequiredHint: 'Hesap başına ayda bir başvuru.',
    authorMonthlyLimit: 'Kayıtlı hesaplar: 30 günde en fazla bir başvuru.',
    authorPointExampleImage: 'Başvuruda örnek görsel zorunlu',
    authorCooldownTitle: 'Şu an başvuramazsınız',
    authorCooldownUntil: 'Sonraki başvuru: {date}',
    authorCooldownError: 'Yeni başvuru için beklemelisiniz.',
    authorPendingReview: 'İncelenen bir başvurunuz var.',
    warningModalTitle: 'Admin mesajı',
    warningModalSubtitle: 'Lütfen kabul veya reddedin',
    warningAccept: 'Kabul ediyorum',
    warningReject: 'Kabul etmiyorum',
    warningYouAccepted: 'Mesajı kabul ettiniz',
    warningYouRejected: 'Mesajı reddettiniz',
    warningReplyLabel: 'Admin\'e yanıtınız (isteğe bağlı)',
    warningReplyPlaceholder: 'Kısa bir mesaj yazın (en fazla 500 karakter)...',
    warningReplyCharCount: '{current} / {max}',
    warningYourReply: 'Yanıtınız',
    warningUserReply: 'Kullanıcı yanıtı',
    categoryAll: 'Tümü',
    categoryPortrait: 'Portreler',
    categoryLandscape: 'Manzara & Doğa',
    categoryArchitecture: 'Mimari',
    categoryLogos: 'Logolar & İkonlar',
    categoryFantasy: 'Fantastik & Sci-Fi',
    categoryWeb: 'Web & UI',
    category3d: '3D & Anime',
    categorySport: 'Spor',
    categoryDigitalArt: 'Dijital Sanat',
    categoryIllustration: 'İllüstrasyon',
    categoryConceptArt: 'Konsept Sanat',
    categoryFood: 'Yiyecek & İçecek',
    categoryFashion: 'Moda & Giyim',
    categoryProductDesign: 'Ürün Tasarımı',
    categoryAbstract: 'Soyut',
    categoryCyberpunk: 'Cyberpunk',
    categorySteampunk: 'Steampunk'
  }
};

const categoryTranslationKeys: Record<string, TranslationKey> = {
  Alla: 'categoryAll',
  'Porträtt': 'categoryPortrait',
  'Landskap & Natur': 'categoryLandscape',
  Arkitektur: 'categoryArchitecture',
  'Logotyper & Ikoner': 'categoryLogos',
  'Fantasy & Sci-Fi': 'categoryFantasy',
  'Webb & UI': 'categoryWeb',
  '3D & Anime': 'category3d',
  Sport: 'categorySport',
  'Digital Art': 'categoryDigitalArt',
  Illustration: 'categoryIllustration',
  Konceptkonst: 'categoryConceptArt',
  'Mat & Dryck': 'categoryFood',
  'Mode & Kläder': 'categoryFashion',
  Produktdesign: 'categoryProductDesign',
  Abstrakt: 'categoryAbstract',
  Cyberpunk: 'categoryCyberpunk',
  Steampunk: 'categorySteampunk'
};

const extraTranslations: Record<LanguageCode, Record<string, string>> = {
  en: {
    customBadge: 'Custom',
    runAndCustomize: 'Run & customize',
    templateVariables: 'Template variables:',
    removeFromFavorites: 'Remove from favorites',
    addToFavorites: 'Add to favorites',
    deletePromptConfirm: 'Are you sure you want to delete "{title}"?',
    deletePromptAdmin: 'Delete prompt (Admin)',
    deleteOwnPrompt: 'Delete your prompt',
    editPromptAdmin: 'Edit prompt (Admin)',
    galleryTemplate: 'Gallery template',
    copied: 'Copied!',
    copyPrompt: 'Copy Prompt',
    noFavoritesTitle: 'No saved favorites',
    noFavoritesText: 'Click the heart on any prompt card in the gallery to save it here for quick access.',
    noCustomTitle: 'No custom prompts yet',
    noCustomText: 'You have not saved any custom prompts with images. Click the button below to add your first one.',
    noResultsTitle: 'No results found',
    noResultsText: 'We could not find any prompts matching "{query}" with your selected filters.',
    createPromptTitle: 'Save New Prompt with Image',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Cinematic Cyberpunk Portrait',
    categoryLabel: 'Category',
    descriptionLabel: 'Short Description',
    descriptionPlaceholder: 'What makes this prompt unique? (optional)',
    aiModelLabel: 'AI Model',
    aspectRatioLabel: 'Aspect Ratio',
    promptTextLabel: 'Prompt Text',
    promptTextTip: 'Tip: [variable] automatically creates input fields!',
    promptTextPlaceholder: 'Write your full AI prompt here...\nExample: A high-end hyperrealistic photo of a [color] sports car driving through [city] at night --ar 16:9',
    negativePromptLabel: 'Negative Prompt',
    negativePromptLongLabel: 'Negative Prompt (avoid these elements)',
    negativePromptPlaceholder: 'e.g. blurry, low quality, distorted, bad anatomy',
    imageUrlLabel: 'Image URL',
    imageUrlLongLabel: 'Image URL (link to reference image)',
    chooseExampleImage: 'Or choose a free example image:',
    imagePreviewAlt: 'Preview',
    imageLoaded: 'Image loaded correctly',
    tagsLabel: 'Tags',
    tagsCommaLabel: 'Tags (comma separated)',
    cancel: 'Cancel',
    savePrompt: 'Save Prompt',
    requiredTitlePromptError: 'Please fill in both title and prompt text.',
    openOriginalImage: 'Open original image',
    savedOn: 'Saved',
    customizeVariables: 'Customize Template Variables',
    customizeVariablesHelp: 'Fill in the fields below to tailor the prompt. The text updates instantly.',
    writeVariable: 'Write {name}...',
    finalPrompt: 'Final AI Prompt',
    characters: 'characters',
    promptCopied: 'Prompt copied!',
    copyCustomPrompt: 'Copy Customized Prompt',
    negativePromptAvoid: 'Negative Prompt (Avoid)',
    adminLoginHeading: 'Admin Login',
    adminInfo: 'As admin, you get full access to create and edit categories, and directly edit title, image and text for every prompt in the gallery.',
    adminPassword: 'Admin Password',
    adminPasswordPlaceholder: 'Enter password...',
    wrongPassword: 'Wrong password. Try again.',
    login: 'Log In',
    manageCategoriesHeading: 'Manage Categories',
    createNewCategory: 'Create New Category',
    categoryPlaceholder: 'e.g. Concept Art',
    create: 'Create',
    existingCategories: 'Existing Categories',
    categoryAddError: 'Could not add. The category already exists or the name is invalid.',
    categoryUpdateError: 'Could not update. The name is invalid or already exists.',
    categoryDeleteConfirm: 'Are you sure you want to delete the category "{name}"? Affected prompts will move to a default category.',
    saveChange: 'Save change',
    editName: 'Edit name',
    deleteCategory: 'Delete category',
    system: 'System',
    editPromptHeading: 'Edit Prompt',
    editPromptRequiredError: 'Title and prompt text are required.',
    currentImageOk: 'Current image link looks good',
    saveChanges: 'Save Changes',
    footerDescription: 'The ultimate platform for saving, optimizing and organizing your best and most secret AI prompts. Free, fast and with 100% local privacy in your browser.',
    vaultSecure: 'Vault Active & Secured',
    explore: 'Explore',
    premiumAiGallery: 'Premium AI Gallery',
    midjourneyPrompts: 'Midjourney v6 Prompts',
    dalleTemplates: 'DALL-E 3 Templates',
    stableDiffusion: 'Stable Diffusion 3',
    information: 'Information',
    privacySecurity: 'Privacy & Security',
    jsonExportImport: 'JSON Export / Import',
    terms: 'Terms of Use',
    helpSupport: 'Help & Support',
    footerRights: 'All rights reserved. Inspired by the best AI galleries.',
    builtWith: 'Built with',
    suggestedNeon: 'Neon Cyberpunk',
    suggestedMountain: 'Epic Mountain Peak',
    suggestedInterior: 'Minimal Interior',
    suggestedGold: 'Abstract Gold',
    suggestedUi: 'Futuristic UI',
    suggestedSpace: 'Space Station',
    authAccount: 'Account',
    authGuest: 'Guest',
    authSignedInAs: 'Signed in as',
    authLoginTitle: 'Log in with email',
    authCreateTitle: 'Create account',
    authEmailLabel: 'Email address',
    authDisplayNameLabel: 'Display name',
    authEmailPlaceholder: 'you@example.com',
    authNamePlaceholder: 'Your name',
    authLoginSubmit: 'Log in',
    authCreateSubmit: 'Create account',
    authGoogle: 'Continue with Google',
    authPopupClosed: 'Sign in was cancelled',
    authGuestButton: 'Continue as guest',
    authLogout: 'Log out',
    authInvalidEmail: 'Enter a valid email address.',
    authMissingName: 'Enter a display name.',
    authExistingAccount: 'An account with this email already exists.',
    authNoAccount: 'No account exists with this email. Create one first.',
    authAccountCreated: 'Account created successfully.',
    authLoggedIn: 'Logged in successfully.',
    authGooglePrompt: 'Enter your Google email address to continue.',
    guestLockedTitle: 'Guest preview only',
    guestLockedText: 'Guests can browse images, names and categories, but prompt text and copying are available only after login.',
    guestLoginCta: 'Log in to unlock prompts',
    authGenericError: 'Something went wrong. Please try again.',
    authWeakPassword: 'Password should be at least 6 characters.',
    authWrongPassword: 'Wrong password. Try again.'
  },
  sv: {
    customBadge: 'Egen',
    runAndCustomize: 'Kör och anpassa',
    templateVariables: 'Mallvariabler:',
    removeFromFavorites: 'Ta bort från favoriter',
    addToFavorites: 'Lägg till i favoriter',
    deletePromptConfirm: 'Är du säker på att du vill ta bort "{title}"?',
    deletePromptAdmin: 'Ta bort prompt (Admin)',
    deleteOwnPrompt: 'Ta bort egen prompt',
    editPromptAdmin: 'Redigera prompt (Admin)',
    galleryTemplate: 'Gallerimall',
    copied: 'Kopierad!',
    copyPrompt: 'Kopiera Prompt',
    noFavoritesTitle: 'Inga sparade favoriter',
    noFavoritesText: 'Klicka på hjärtat på något av prompt-korten i galleriet för att spara dem här för snabb åtkomst.',
    noCustomTitle: 'Inga egna prompter ännu',
    noCustomText: 'Du har inte sparat några egna prompter med bilder. Klicka på knappen nedan för att lägga till din första!',
    noResultsTitle: 'Inga resultat hittades',
    noResultsText: 'Vi kunde inte hitta några prompter som matchade "{query}" med dina valda filter.',
    createPromptTitle: 'Spara Ny Prompt med Bild',
    titleLabel: 'Titel',
    titlePlaceholder: 't.ex. Cinematiskt Cyberpunk Porträtt',
    categoryLabel: 'Kategori',
    descriptionLabel: 'Kort Beskrivning',
    descriptionPlaceholder: 'Vad gör denna prompt unik? (valfritt)',
    aiModelLabel: 'AI-Modell',
    aspectRatioLabel: 'Bildförhållande',
    promptTextLabel: 'Prompt Text',
    promptTextTip: 'Tips: [variabel] skapar automatiskt ifyllnadsfält!',
    promptTextPlaceholder: 'Skriv din fullständiga AI-prompt här...\nExempel: A high-end hyperrealistic photo of a [färg] sports car driving through [stad] at night --ar 16:9',
    negativePromptLabel: 'Negativ Prompt',
    negativePromptLongLabel: 'Negativ Prompt (undvik dessa element)',
    negativePromptPlaceholder: 't.ex. blurry, low quality, distorted, bad anatomy',
    imageUrlLabel: 'Bild-URL',
    imageUrlLongLabel: 'Bild-URL (länk till referensbild)',
    chooseExampleImage: 'Eller välj en gratis exempelbild:',
    imagePreviewAlt: 'Förhandsgranskning',
    imageLoaded: 'Bilden laddas korrekt',
    tagsLabel: 'Taggar',
    tagsCommaLabel: 'Taggar (kommaseparerade)',
    cancel: 'Avbryt',
    savePrompt: 'Spara Prompt',
    requiredTitlePromptError: 'Vänligen fyll i både titel och prompt-text.',
    openOriginalImage: 'Öppna originalbild',
    savedOn: 'Sparad',
    customizeVariables: 'Anpassa Mallvariabler',
    customizeVariablesHelp: 'Fyll i fälten nedan för att skräddarsy prompten. Texten uppdateras direkt.',
    writeVariable: 'Skriv {name}...',
    finalPrompt: 'Slutgiltig AI-Prompt',
    characters: 'tecken',
    promptCopied: 'Prompten har kopierats!',
    copyCustomPrompt: 'Kopiera Anpassad Prompt',
    negativePromptAvoid: 'Negativ Prompt (Undvik)',
    adminLoginHeading: 'Admin Inloggning',
    adminInfo: 'Som admin får du full tillgång till att skapa och redigera kategorier, samt direkt redigera titel, bild och text för samtliga prompter i galleriet.',
    adminPassword: 'Administratörslösenord',
    adminPasswordPlaceholder: 'Ange lösenord...',
    wrongPassword: 'Felaktigt lösenord. Försök igen.',
    login: 'Logga In',
    manageCategoriesHeading: 'Hantera Kategorier',
    createNewCategory: 'Skapa Ny Kategori',
    categoryPlaceholder: 't.ex. Konceptkonst',
    create: 'Skapa',
    existingCategories: 'Befintliga Kategorier',
    categoryAddError: 'Kunde inte lägga till. Kategorin finns redan eller namnet är ogiltigt.',
    categoryUpdateError: 'Kunde inte uppdatera. Namnet är ogiltigt eller finns redan.',
    categoryDeleteConfirm: 'Är du säker på att du vill ta bort kategorin "{name}"? Berörda prompter flyttas till en standardkategori.',
    saveChange: 'Spara ändring',
    editName: 'Redigera namn',
    deleteCategory: 'Ta bort kategori',
    system: 'System',
    editPromptHeading: 'Redigera Prompt',
    editPromptRequiredError: 'Titel och prompt-text måste fyllas i.',
    currentImageOk: 'Nuvarande bildlänk stämmer',
    saveChanges: 'Spara Ändringar',
    footerDescription: 'Den ultimata plattformen för att spara, optimera och organisera dina bästa och mest hemliga AI-prompter. Helt gratis, blixtsnabbt och med 100% lokal integritet i din webbläsare.',
    vaultSecure: 'Valv Aktivt & Säkrat',
    explore: 'Utforska',
    premiumAiGallery: 'Premium AI Galleri',
    midjourneyPrompts: 'Midjourney v6 Prompter',
    dalleTemplates: 'DALL-E 3 Mallar',
    stableDiffusion: 'Stable Diffusion 3',
    information: 'Information',
    privacySecurity: 'Integritet & Säkerhet',
    jsonExportImport: 'JSON Export / Import',
    terms: 'Användarvillkor',
    helpSupport: 'Hjälp & Support',
    footerRights: 'Alla rättigheter reserverade. Inspirerad av de bästa AI-gallerierna.',
    builtWith: 'Byggd med',
    suggestedNeon: 'Neon Cyberpunk',
    suggestedMountain: 'Episk Bergstopp',
    suggestedInterior: 'Minimalistisk Inredning',
    suggestedGold: 'Abstrakt Guld',
    suggestedUi: 'Futuristisk UI',
    suggestedSpace: 'Rymdstation',
    authAccount: 'Konto',
    authGuest: 'Gäst',
    authSignedInAs: 'Inloggad som',
    authLoginTitle: 'Logga in med e-post',
    authCreateTitle: 'Skapa konto',
    authEmailLabel: 'E-postadress',
    authDisplayNameLabel: 'Visningsnamn',
    authEmailPlaceholder: 'du@example.com',
    authNamePlaceholder: 'Ditt namn',
    authLoginSubmit: 'Logga in',
    authCreateSubmit: 'Skapa konto',
    authGoogle: 'Fortsätt med Google',
    authPopupClosed: 'Inloggningen avbröts',
    authGuestButton: 'Fortsätt som gäst',
    authLogout: 'Logga ut',
    authInvalidEmail: 'Ange en giltig e-postadress.',
    authMissingName: 'Ange ett visningsnamn.',
    authExistingAccount: 'Ett konto med denna e-post finns redan.',
    authNoAccount: 'Det finns inget konto med denna e-post. Skapa ett konto först.',
    authAccountCreated: 'Kontot skapades.',
    authLoggedIn: 'Du är inloggad.',
    authGooglePrompt: 'Ange din Google-e-postadress för att fortsätta.',
    guestLockedTitle: 'Endast gästförhandsvisning',
    guestLockedText: 'Gäster kan bläddra bland bilder, namn och kategorier, men prompt-text och kopiering kräver inloggning.',
    guestLoginCta: 'Logga in för att låsa upp prompts'
  },
  de: {
    customBadge: 'Eigen',
    runAndCustomize: 'Starten & anpassen',
    templateVariables: 'Vorlagenvariablen:',
    removeFromFavorites: 'Aus Favoriten entfernen',
    addToFavorites: 'Zu Favoriten hinzufügen',
    deletePromptConfirm: 'Möchtest du "{title}" wirklich löschen?',
    deletePromptAdmin: 'Prompt löschen (Admin)',
    deleteOwnPrompt: 'Eigenen Prompt löschen',
    editPromptAdmin: 'Prompt bearbeiten (Admin)',
    galleryTemplate: 'Galerievorlage',
    copied: 'Kopiert!',
    copyPrompt: 'Prompt kopieren',
    noFavoritesTitle: 'Keine Favoriten gespeichert',
    noFavoritesText: 'Klicke auf das Herz einer Prompt-Karte, um sie hier für schnellen Zugriff zu speichern.',
    noCustomTitle: 'Noch keine eigenen Prompts',
    noCustomText: 'Du hast noch keine eigenen Prompts mit Bildern gespeichert. Klicke unten, um den ersten hinzuzufügen.',
    noResultsTitle: 'Keine Ergebnisse gefunden',
    noResultsText: 'Wir konnten keine Prompts finden, die "{query}" mit deinen Filtern entsprechen.',
    createPromptTitle: 'Neuen Prompt mit Bild speichern',
    titleLabel: 'Titel',
    titlePlaceholder: 'z.B. Cinematisches Cyberpunk-Porträt',
    categoryLabel: 'Kategorie',
    descriptionLabel: 'Kurze Beschreibung',
    descriptionPlaceholder: 'Was macht diesen Prompt besonders? (optional)',
    aiModelLabel: 'KI-Modell',
    aspectRatioLabel: 'Seitenverhältnis',
    promptTextLabel: 'Prompt Text',
    promptTextTip: 'Tipp: [variable] erstellt automatisch Eingabefelder!',
    promptTextPlaceholder: 'Schreibe hier deinen vollständigen KI-Prompt...\nBeispiel: A high-end hyperrealistic photo of a [color] sports car driving through [city] at night --ar 16:9',
    negativePromptLabel: 'Negativer Prompt',
    negativePromptLongLabel: 'Negativer Prompt (diese Elemente vermeiden)',
    negativePromptPlaceholder: 'z.B. blurry, low quality, distorted, bad anatomy',
    imageUrlLabel: 'Bild-URL',
    imageUrlLongLabel: 'Bild-URL (Link zum Referenzbild)',
    chooseExampleImage: 'Oder wähle ein kostenloses Beispielbild:',
    imagePreviewAlt: 'Vorschau',
    imageLoaded: 'Bild wurde korrekt geladen',
    tagsLabel: 'Tags',
    tagsCommaLabel: 'Tags (kommagetrennt)',
    cancel: 'Abbrechen',
    savePrompt: 'Prompt speichern',
    requiredTitlePromptError: 'Bitte fülle Titel und Prompt-Text aus.',
    openOriginalImage: 'Originalbild öffnen',
    savedOn: 'Gespeichert',
    customizeVariables: 'Vorlagenvariablen anpassen',
    customizeVariablesHelp: 'Fülle die Felder aus, um den Prompt anzupassen. Der Text aktualisiert sich sofort.',
    writeVariable: '{name} eingeben...',
    finalPrompt: 'Finaler KI-Prompt',
    characters: 'Zeichen',
    promptCopied: 'Prompt wurde kopiert!',
    copyCustomPrompt: 'Angepassten Prompt kopieren',
    negativePromptAvoid: 'Negativer Prompt (Vermeiden)',
    adminLoginHeading: 'Admin-Login',
    adminInfo: 'Als Admin kannst du Kategorien erstellen und bearbeiten sowie Titel, Bild und Text aller Prompts direkt ändern.',
    adminPassword: 'Admin-Passwort',
    adminPasswordPlaceholder: 'Passwort eingeben...',
    wrongPassword: 'Falsches Passwort. Versuche es erneut.',
    login: 'Einloggen',
    manageCategoriesHeading: 'Kategorien verwalten',
    createNewCategory: 'Neue Kategorie erstellen',
    categoryPlaceholder: 'z.B. Concept Art',
    create: 'Erstellen',
    existingCategories: 'Bestehende Kategorien',
    categoryAddError: 'Konnte nicht hinzugefügt werden. Die Kategorie existiert bereits oder der Name ist ungültig.',
    categoryUpdateError: 'Konnte nicht aktualisiert werden. Der Name ist ungültig oder existiert bereits.',
    categoryDeleteConfirm: 'Möchtest du die Kategorie "{name}" wirklich löschen? Betroffene Prompts werden in eine Standardkategorie verschoben.',
    saveChange: 'Änderung speichern',
    editName: 'Namen bearbeiten',
    deleteCategory: 'Kategorie löschen',
    system: 'System',
    editPromptHeading: 'Prompt bearbeiten',
    editPromptRequiredError: 'Titel und Prompt-Text sind erforderlich.',
    currentImageOk: 'Aktueller Bildlink sieht gut aus',
    saveChanges: 'Änderungen speichern',
    footerDescription: 'Die ultimative Plattform zum Speichern, Optimieren und Organisieren deiner besten und geheimsten KI-Prompts. Kostenlos, schnell und mit 100% lokaler Privatsphäre im Browser.',
    vaultSecure: 'Tresor aktiv & gesichert',
    explore: 'Entdecken',
    premiumAiGallery: 'Premium KI-Galerie',
    midjourneyPrompts: 'Midjourney v6 Prompts',
    dalleTemplates: 'DALL-E 3 Vorlagen',
    stableDiffusion: 'Stable Diffusion 3',
    information: 'Information',
    privacySecurity: 'Datenschutz & Sicherheit',
    jsonExportImport: 'JSON Export / Import',
    terms: 'Nutzungsbedingungen',
    helpSupport: 'Hilfe & Support',
    footerRights: 'Alle Rechte vorbehalten. Inspiriert von den besten KI-Galerien.',
    builtWith: 'Gebaut mit',
    suggestedNeon: 'Neon Cyberpunk',
    suggestedMountain: 'Epischer Berggipfel',
    suggestedInterior: 'Minimalistisches Interior',
    suggestedGold: 'Abstraktes Gold',
    suggestedUi: 'Futuristische UI',
    suggestedSpace: 'Raumstation',
    authAccount: 'Konto',
    authGuest: 'Gast',
    authSignedInAs: 'Eingeloggt als',
    authLoginTitle: 'Mit E-Mail einloggen',
    authCreateTitle: 'Konto erstellen',
    authEmailLabel: 'E-Mail-Adresse',
    authDisplayNameLabel: 'Anzeigename',
    authEmailPlaceholder: 'du@example.com',
    authNamePlaceholder: 'Dein Name',
    authLoginSubmit: 'Einloggen',
    authCreateSubmit: 'Konto erstellen',
    authGoogle: 'Mit Google fortfahren',
    authPopupClosed: 'Anmeldung abgebrochen',
    authGuestButton: 'Als Gast fortfahren',
    authLogout: 'Abmelden',
    authInvalidEmail: 'Gib eine gültige E-Mail-Adresse ein.',
    authMissingName: 'Gib einen Anzeigenamen ein.',
    authExistingAccount: 'Ein Konto mit dieser E-Mail existiert bereits.',
    authNoAccount: 'Es gibt kein Konto mit dieser E-Mail. Erstelle zuerst eins.',
    authAccountCreated: 'Konto erfolgreich erstellt.',
    authLoggedIn: 'Erfolgreich eingeloggt.',
    authGooglePrompt: 'Gib deine Google-E-Mail-Adresse ein, um fortzufahren.',
    guestLockedTitle: 'Nur Gastvorschau',
    guestLockedText: 'Gäste können Bilder, Namen und Kategorien ansehen, aber Prompt-Text und Kopieren sind nur nach Login verfügbar.',
    guestLoginCta: 'Einloggen, um Prompts freizuschalten'
  },
  es: {
    customBadge: 'Propio',
    runAndCustomize: 'Ejecutar y personalizar',
    templateVariables: 'Variables de plantilla:',
    removeFromFavorites: 'Quitar de favoritos',
    addToFavorites: 'Añadir a favoritos',
    deletePromptConfirm: '¿Seguro que quieres eliminar "{title}"?',
    deletePromptAdmin: 'Eliminar prompt (Admin)',
    deleteOwnPrompt: 'Eliminar tu prompt',
    editPromptAdmin: 'Editar prompt (Admin)',
    galleryTemplate: 'Plantilla de galería',
    copied: '¡Copiado!',
    copyPrompt: 'Copiar Prompt',
    noFavoritesTitle: 'No hay favoritos guardados',
    noFavoritesText: 'Haz clic en el corazón de cualquier prompt para guardarlo aquí y acceder rápido.',
    noCustomTitle: 'Aún no hay prompts propios',
    noCustomText: 'Todavía no has guardado prompts propios con imágenes. Haz clic abajo para añadir el primero.',
    noResultsTitle: 'No se encontraron resultados',
    noResultsText: 'No encontramos prompts que coincidan con "{query}" y tus filtros.',
    createPromptTitle: 'Guardar Nuevo Prompt con Imagen',
    titleLabel: 'Título',
    titlePlaceholder: 'p. ej. Retrato cyberpunk cinematográfico',
    categoryLabel: 'Categoría',
    descriptionLabel: 'Descripción corta',
    descriptionPlaceholder: '¿Qué hace único este prompt? (opcional)',
    aiModelLabel: 'Modelo de IA',
    aspectRatioLabel: 'Relación de aspecto',
    promptTextLabel: 'Texto del Prompt',
    promptTextTip: 'Consejo: [variable] crea campos automáticamente.',
    promptTextPlaceholder: 'Escribe aquí tu prompt completo...\nEjemplo: A high-end hyperrealistic photo of a [color] sports car driving through [city] at night --ar 16:9',
    negativePromptLabel: 'Prompt negativo',
    negativePromptLongLabel: 'Prompt negativo (evita estos elementos)',
    negativePromptPlaceholder: 'p. ej. blurry, low quality, distorted, bad anatomy',
    imageUrlLabel: 'URL de imagen',
    imageUrlLongLabel: 'URL de imagen (enlace a imagen de referencia)',
    chooseExampleImage: 'O elige una imagen de ejemplo gratuita:',
    imagePreviewAlt: 'Vista previa',
    imageLoaded: 'La imagen se cargó correctamente',
    tagsLabel: 'Etiquetas',
    tagsCommaLabel: 'Etiquetas (separadas por comas)',
    cancel: 'Cancelar',
    savePrompt: 'Guardar Prompt',
    requiredTitlePromptError: 'Por favor completa título y texto del prompt.',
    openOriginalImage: 'Abrir imagen original',
    savedOn: 'Guardado',
    customizeVariables: 'Personalizar variables',
    customizeVariablesHelp: 'Rellena los campos para adaptar el prompt. El texto se actualiza al instante.',
    writeVariable: 'Escribe {name}...',
    finalPrompt: 'Prompt final de IA',
    characters: 'caracteres',
    promptCopied: '¡Prompt copiado!',
    copyCustomPrompt: 'Copiar Prompt Personalizado',
    negativePromptAvoid: 'Prompt negativo (Evitar)',
    adminLoginHeading: 'Inicio de Admin',
    adminInfo: 'Como admin, puedes crear y editar categorías y modificar directamente título, imagen y texto de todos los prompts.',
    adminPassword: 'Contraseña de Admin',
    adminPasswordPlaceholder: 'Introduce contraseña...',
    wrongPassword: 'Contraseña incorrecta. Inténtalo de nuevo.',
    login: 'Iniciar sesión',
    manageCategoriesHeading: 'Gestionar Categorías',
    createNewCategory: 'Crear Nueva Categoría',
    categoryPlaceholder: 'p. ej. Arte conceptual',
    create: 'Crear',
    existingCategories: 'Categorías existentes',
    categoryAddError: 'No se pudo añadir. La categoría ya existe o el nombre no es válido.',
    categoryUpdateError: 'No se pudo actualizar. El nombre no es válido o ya existe.',
    categoryDeleteConfirm: '¿Seguro que quieres eliminar la categoría "{name}"? Los prompts afectados se moverán a una categoría predeterminada.',
    saveChange: 'Guardar cambio',
    editName: 'Editar nombre',
    deleteCategory: 'Eliminar categoría',
    system: 'Sistema',
    editPromptHeading: 'Editar Prompt',
    editPromptRequiredError: 'Título y texto del prompt son obligatorios.',
    currentImageOk: 'El enlace de imagen actual se ve correcto',
    saveChanges: 'Guardar Cambios',
    footerDescription: 'La plataforma definitiva para guardar, optimizar y organizar tus mejores y más secretos prompts de IA. Gratis, rápida y con privacidad 100% local en tu navegador.',
    vaultSecure: 'Bóveda activa y segura',
    explore: 'Explorar',
    premiumAiGallery: 'Galería Premium de IA',
    midjourneyPrompts: 'Prompts Midjourney v6',
    dalleTemplates: 'Plantillas DALL-E 3',
    stableDiffusion: 'Stable Diffusion 3',
    information: 'Información',
    privacySecurity: 'Privacidad y Seguridad',
    jsonExportImport: 'JSON Export / Import',
    terms: 'Términos de Uso',
    helpSupport: 'Ayuda y Soporte',
    footerRights: 'Todos los derechos reservados. Inspirado en las mejores galerías de IA.',
    builtWith: 'Creado con',
    suggestedNeon: 'Neón Cyberpunk',
    suggestedMountain: 'Pico de montaña épico',
    suggestedInterior: 'Interior minimalista',
    suggestedGold: 'Oro abstracto',
    suggestedUi: 'UI futurista',
    suggestedSpace: 'Estación espacial',
    authAccount: 'Cuenta',
    authGuest: 'Invitado',
    authSignedInAs: 'Sesión iniciada como',
    authLoginTitle: 'Iniciar sesión con email',
    authCreateTitle: 'Crear cuenta',
    authEmailLabel: 'Correo electrónico',
    authDisplayNameLabel: 'Nombre público',
    authEmailPlaceholder: 'tu@example.com',
    authNamePlaceholder: 'Tu nombre',
    authLoginSubmit: 'Iniciar sesión',
    authCreateSubmit: 'Crear cuenta',
    authGoogle: 'Continuar con Google',
    authPopupClosed: 'Inicio de sesión cancelado',
    authGuestButton: 'Continuar como invitado',
    authLogout: 'Cerrar sesión',
    authInvalidEmail: 'Introduce un correo válido.',
    authMissingName: 'Introduce un nombre público.',
    authExistingAccount: 'Ya existe una cuenta con este correo.',
    authNoAccount: 'No existe una cuenta con este correo. Crea una primero.',
    authAccountCreated: 'Cuenta creada correctamente.',
    authLoggedIn: 'Sesión iniciada correctamente.',
    authGooglePrompt: 'Introduce tu correo de Google para continuar.',
    guestLockedTitle: 'Solo vista previa de invitado',
    guestLockedText: 'Los invitados pueden ver imágenes, nombres y categorías, pero el texto del prompt y la copia requieren iniciar sesión.',
    guestLoginCta: 'Inicia sesión para desbloquear prompts'
  },
  tr: {
    customBadge: 'Özel',
    runAndCustomize: 'Çalıştır ve özelleştir',
    templateVariables: 'Şablon değişkenleri:',
    removeFromFavorites: 'Favorilerden kaldır',
    addToFavorites: 'Favorilere ekle',
    deletePromptConfirm: '"{title}" promptunu silmek istediğine emin misin?',
    deletePromptAdmin: 'Promptu sil (Admin)',
    deleteOwnPrompt: 'Kendi promptunu sil',
    editPromptAdmin: 'Promptu düzenle (Admin)',
    galleryTemplate: 'Galeri şablonu',
    copied: 'Kopyalandı!',
    copyPrompt: 'Promptu Kopyala',
    noFavoritesTitle: 'Kaydedilmiş favori yok',
    noFavoritesText: 'Hızlı erişim için galerideki herhangi bir prompt kartındaki kalbe tıkla.',
    noCustomTitle: 'Henüz özel prompt yok',
    noCustomText: 'Henüz görselli özel prompt kaydetmedin. İlkini eklemek için aşağıdaki düğmeye tıkla.',
    noResultsTitle: 'Sonuç bulunamadı',
    noResultsText: '"{query}" ile eşleşen ve seçili filtrelere uyan prompt bulamadık.',
    createPromptTitle: 'Görselli Yeni Prompt Kaydet',
    titleLabel: 'Başlık',
    titlePlaceholder: 'örn. Sinematik Cyberpunk Portre',
    categoryLabel: 'Kategori',
    descriptionLabel: 'Kısa Açıklama',
    descriptionPlaceholder: 'Bu promptu özel yapan nedir? (isteğe bağlı)',
    aiModelLabel: 'AI Modeli',
    aspectRatioLabel: 'En-boy oranı',
    promptTextLabel: 'Prompt Metni',
    promptTextTip: 'İpucu: [değişken] otomatik giriş alanları oluşturur!',
    promptTextPlaceholder: 'Tam AI promptunu buraya yaz...\nÖrnek: A high-end hyperrealistic photo of a [color] sports car driving through [city] at night --ar 16:9',
    negativePromptLabel: 'Negatif Prompt',
    negativePromptLongLabel: 'Negatif Prompt (bu öğelerden kaçın)',
    negativePromptPlaceholder: 'örn. blurry, low quality, distorted, bad anatomy',
    imageUrlLabel: 'Görsel URL',
    imageUrlLongLabel: 'Görsel URL (referans görsel bağlantısı)',
    chooseExampleImage: 'Ya da ücretsiz örnek görsel seç:',
    imagePreviewAlt: 'Önizleme',
    imageLoaded: 'Görsel doğru yüklendi',
    tagsLabel: 'Etiketler',
    tagsCommaLabel: 'Etiketler (virgülle ayrılmış)',
    cancel: 'İptal',
    savePrompt: 'Promptu Kaydet',
    requiredTitlePromptError: 'Lütfen başlık ve prompt metnini doldur.',
    openOriginalImage: 'Orijinal görseli aç',
    savedOn: 'Kaydedildi',
    customizeVariables: 'Şablon Değişkenlerini Özelleştir',
    customizeVariablesHelp: 'Promptu uyarlamak için alanları doldur. Metin anında güncellenir.',
    writeVariable: '{name} yaz...',
    finalPrompt: 'Son AI Promptu',
    characters: 'karakter',
    promptCopied: 'Prompt kopyalandı!',
    copyCustomPrompt: 'Özelleştirilmiş Promptu Kopyala',
    negativePromptAvoid: 'Negatif Prompt (Kaçın)',
    adminLoginHeading: 'Admin Girişi',
    adminInfo: 'Admin olarak kategorileri oluşturup düzenleyebilir, galerideki tüm promptların başlık, görsel ve metinlerini doğrudan değiştirebilirsin.',
    adminPassword: 'Admin Şifresi',
    adminPasswordPlaceholder: 'Şifre gir...',
    wrongPassword: 'Yanlış şifre. Tekrar dene.',
    login: 'Giriş Yap',
    manageCategoriesHeading: 'Kategorileri Yönet',
    createNewCategory: 'Yeni Kategori Oluştur',
    categoryPlaceholder: 'örn. Konsept Sanat',
    create: 'Oluştur',
    existingCategories: 'Mevcut Kategoriler',
    categoryAddError: 'Eklenemedi. Kategori zaten var veya ad geçersiz.',
    categoryUpdateError: 'Güncellenemedi. Ad geçersiz veya zaten var.',
    categoryDeleteConfirm: '"{name}" kategorisini silmek istediğine emin misin? İlgili promptlar varsayılan kategoriye taşınır.',
    saveChange: 'Değişikliği kaydet',
    editName: 'Adı düzenle',
    deleteCategory: 'Kategoriyi sil',
    system: 'Sistem',
    editPromptHeading: 'Promptu Düzenle',
    editPromptRequiredError: 'Başlık ve prompt metni zorunludur.',
    currentImageOk: 'Mevcut görsel bağlantısı iyi görünüyor',
    saveChanges: 'Değişiklikleri Kaydet',
    footerDescription: 'En iyi ve en gizli AI promptlarını kaydetmek, optimize etmek ve düzenlemek için nihai platform. Ücretsiz, hızlı ve tarayıcında %100 yerel gizlilikle.',
    vaultSecure: 'Kasa Aktif ve Güvenli',
    explore: 'Keşfet',
    premiumAiGallery: 'Premium AI Galerisi',
    midjourneyPrompts: 'Midjourney v6 Promptları',
    dalleTemplates: 'DALL-E 3 Şablonları',
    stableDiffusion: 'Stable Diffusion 3',
    information: 'Bilgi',
    privacySecurity: 'Gizlilik ve Güvenlik',
    jsonExportImport: 'JSON Dışa / İçe Aktar',
    terms: 'Kullanım Şartları',
    helpSupport: 'Yardım ve Destek',
    footerRights: 'Tüm hakları saklıdır. En iyi AI galerilerinden ilham alınmıştır.',
    builtWith: 'Şununla oluşturuldu',
    suggestedNeon: 'Neon Cyberpunk',
    suggestedMountain: 'Epik Dağ Zirvesi',
    suggestedInterior: 'Minimal İç Mekan',
    suggestedGold: 'Soyut Altın',
    suggestedUi: 'Fütüristik UI',
    suggestedSpace: 'Uzay İstasyonu',
    authAccount: 'Hesap',
    authGuest: 'Misafir',
    authSignedInAs: 'Giriş yapan',
    authLoginTitle: 'E-posta ile giriş yap',
    authCreateTitle: 'Hesap oluştur',
    authEmailLabel: 'E-posta adresi',
    authDisplayNameLabel: 'Görünen isim',
    authEmailPlaceholder: 'sen@example.com',
    authNamePlaceholder: 'Adın',
    authLoginSubmit: 'Giriş yap',
    authCreateSubmit: 'Hesap oluştur',
    authGoogle: 'Google ile devam et',
    authPopupClosed: 'Giriş iptal edildi',
    authGuestButton: 'Misafir olarak devam et',
    authLogout: 'Çıkış yap',
    authInvalidEmail: 'Geçerli bir e-posta adresi gir.',
    authMissingName: 'Görünen isim gir.',
    authExistingAccount: 'Bu e-posta ile zaten bir hesap var.',
    authNoAccount: 'Bu e-posta ile hesap yok. Önce hesap oluştur.',
    authAccountCreated: 'Hesap başarıyla oluşturuldu.',
    authLoggedIn: 'Başarıyla giriş yapıldı.',
    authGooglePrompt: 'Devam etmek için Google e-postanı gir.',
    guestLockedTitle: 'Sadece misafir önizlemesi',
    guestLockedText: 'Misafirler görselleri, isimleri ve kategorileri görebilir; prompt metni ve kopyalama için giriş gerekir.',
    guestLoginCta: 'Promptları açmak için giriş yap'
  }
};

const suggestedImageTranslationKeys: Record<string, string> = {
  'Neon Cyberpunk': 'suggestedNeon',
  'Episk Bergstopp': 'suggestedMountain',
  'Minimalistisk Inredning': 'suggestedInterior',
  'Abstrakt Guld': 'suggestedGold',
  'Futuristisk UI': 'suggestedUi',
  Rymdstation: 'suggestedSpace'
};

const tagTranslations: Record<LanguageCode, Record<string, string>> = {
  en: {
    Porträtt: 'Portrait', Cinematisk: 'Cinematic', Arkitektur: 'Architecture', Skandinavisk: 'Scandinavian', Lyx: 'Luxury', Exteriör: 'Exterior', Natur: 'Nature', Magisk: 'Magic', Konceptkonst: 'Concept Art', Belysning: 'Lighting', Logotyp: 'Logo', Vektor: 'Vector', Webbdesign: 'Web Design', Karaktär: 'Character', Gullig: 'Cute', Landskap: 'Landscape', Berg: 'Mountain', Solnedgång: 'Sunset', Fotografi: 'Photography', Abstrakt: 'Abstract', Guld: 'Gold', Bakgrund: 'Background', Textur: 'Texture', Inredning: 'Interior Design', Interiör: 'Interior', Vardagsrum: 'Living Room'
  },
  sv: {},
  de: {
    Porträtt: 'Porträt', Cinematisk: 'Cinematisch', Arkitektur: 'Architektur', Skandinavisk: 'Skandinavisch', Lyx: 'Luxus', Exteriör: 'Exterieur', Natur: 'Natur', Magisk: 'Magisch', Konceptkonst: 'Concept Art', Belysning: 'Beleuchtung', Logotyp: 'Logo', Vektor: 'Vektor', Webbdesign: 'Webdesign', Karaktär: 'Charakter', Gullig: 'Niedlich', Landskap: 'Landschaft', Berg: 'Berg', Solnedgång: 'Sonnenuntergang', Fotografi: 'Fotografie', Abstrakt: 'Abstrakt', Guld: 'Gold', Bakgrund: 'Hintergrund', Textur: 'Textur', Inredning: 'Interior Design', Interiör: 'Interieur', Vardagsrum: 'Wohnzimmer'
  },
  es: {
    Porträtt: 'Retrato', Cinematisk: 'Cinemático', Arkitektur: 'Arquitectura', Skandinavisk: 'Escandinavo', Lyx: 'Lujo', Exteriör: 'Exterior', Natur: 'Naturaleza', Magisk: 'Mágico', Konceptkonst: 'Arte conceptual', Belysning: 'Iluminación', Logotyp: 'Logotipo', Vektor: 'Vector', Webbdesign: 'Diseño web', Karaktär: 'Personaje', Gullig: 'Tierno', Landskap: 'Paisaje', Berg: 'Montaña', Solnedgång: 'Atardecer', Fotografi: 'Fotografía', Abstrakt: 'Abstracto', Guld: 'Oro', Bakgrund: 'Fondo', Textur: 'Textura', Inredning: 'Diseño interior', Interiör: 'Interior', Vardagsrum: 'Sala de estar'
  },
  tr: {
    Porträtt: 'Portre', Cinematisk: 'Sinematik', Arkitektur: 'Mimari', Skandinavisk: 'İskandinav', Lyx: 'Lüks', Exteriör: 'Dış Mekan', Natur: 'Doğa', Magisk: 'Büyülü', Konceptkonst: 'Konsept Sanat', Belysning: 'Işıklandırma', Logotyp: 'Logo', Vektor: 'Vektör', Webbdesign: 'Web Tasarım', Karaktär: 'Karakter', Gullig: 'Sevimli', Landskap: 'Manzara', Berg: 'Dağ', Solnedgång: 'Gün Batımı', Fotografi: 'Fotoğrafçılık', Abstrakt: 'Soyut', Guld: 'Altın', Bakgrund: 'Arka Plan', Textur: 'Doku', Inredning: 'İç Tasarım', Interiör: 'İç Mekan', Vardagsrum: 'Oturma Odası'
  }
};

const promptTranslations: Record<LanguageCode, Record<string, { title: string; description: string }>> = {
  en: {
    'prompt-1': { title: 'Cinematic Cyberpunk Portrait', description: 'A hyperrealistic portrait with dramatic neon lighting and intricate futuristic details. Perfect for character design and concept art.' },
    'prompt-2': { title: 'Minimalist Scandinavian Villa', description: 'Architectural visualization of a modern home in nature with natural light and clean lines.' },
    'prompt-3': { title: 'Magical Glowing Fantasy Forest', description: 'A captivating dreamlike environment filled with bioluminescent plants and mysterious light.' },
    'prompt-4': { title: 'Sleek Vector Tech Logo', description: 'Modern clean logo design for startups and tech companies. Scalable and minimalist.' },
    'prompt-5': { title: 'SaaS Dashboard UI & Web Design', description: 'Professional clean interface design for web applications. Perfect inspiration for developers.' },
    'prompt-6': { title: 'Cute 3D Pixar-Style Character', description: 'An extremely cute expressive 3D character with soft textures and beautiful lighting.' },
    'prompt-7': { title: 'Epic Mountain Landscape at Sunset', description: 'A breathtaking nature view with dramatic clouds and golden sun rays hitting the peaks.' },
    'prompt-8': { title: 'Abstract Liquid Gold & Black', description: 'Exclusive sophisticated abstract art. Perfect as a background for luxury brands and presentations.' },
    'prompt-9': { title: 'Luxury Interior in a Modern Apartment', description: 'Interior design of an elegant living room with exclusive furniture and soft mood lighting.' }
  },
  sv: {},
  de: {
    'prompt-1': { title: 'Cinematisches Cyberpunk-Porträt', description: 'Ein hyperrealistisches Porträt mit dramatischem Neonlicht und futuristischen Details. Perfekt für Charakterdesign und Concept Art.' },
    'prompt-2': { title: 'Minimalistische skandinavische Villa', description: 'Architekturvisualisierung eines modernen Hauses in der Natur mit natürlichem Licht und klaren Linien.' },
    'prompt-3': { title: 'Magisch leuchtender Fantasy-Wald', description: 'Eine faszinierende traumhafte Umgebung voller biolumineszenter Pflanzen und mystischer Lichter.' },
    'prompt-4': { title: 'Elegantes Vektor-Tech-Logo', description: 'Modernes klares Logodesign für Startups und Tech-Unternehmen. Skalierbar und minimalistisch.' },
    'prompt-5': { title: 'SaaS Dashboard UI & Webdesign', description: 'Professionelles klares Interface-Design für Webanwendungen. Perfekte Inspiration für Entwickler.' },
    'prompt-6': { title: 'Niedlicher 3D-Charakter im Pixar-Stil', description: 'Ein besonders niedlicher 3D-Charakter mit weichen Texturen und schönem Licht.' },
    'prompt-7': { title: 'Epische Berglandschaft bei Sonnenuntergang', description: 'Eine atemberaubende Naturansicht mit dramatischen Wolken und goldenen Sonnenstrahlen.' },
    'prompt-8': { title: 'Abstraktes flüssiges Gold & Schwarz', description: 'Exklusive abstrakte Kunst. Perfekt als Hintergrund für Luxusmarken und Präsentationen.' },
    'prompt-9': { title: 'Luxuriöses Interieur in moderner Wohnung', description: 'Interior Design eines eleganten Wohnzimmers mit exklusiven Möbeln und sanfter Beleuchtung.' }
  },
  es: {
    'prompt-1': { title: 'Retrato Cyberpunk Cinematográfico', description: 'Un retrato hiperrealista con iluminación neón dramática y detalles futuristas. Perfecto para diseño de personajes y arte conceptual.' },
    'prompt-2': { title: 'Villa Escandinava Minimalista', description: 'Visualización arquitectónica de una casa moderna en la naturaleza con luz natural y líneas limpias.' },
    'prompt-3': { title: 'Bosque Fantástico Mágico y Brillante', description: 'Un entorno onírico cautivador lleno de plantas bioluminiscentes y luces misteriosas.' },
    'prompt-4': { title: 'Logo Tech Vectorial Elegante', description: 'Diseño de logo moderno y limpio para startups y empresas tecnológicas. Escalable y minimalista.' },
    'prompt-5': { title: 'Dashboard SaaS UI & Diseño Web', description: 'Diseño de interfaz profesional y limpio para aplicaciones web. Inspiración perfecta para desarrolladores.' },
    'prompt-6': { title: 'Personaje 3D Estilo Pixar Tierno', description: 'Un personaje 3D extremadamente tierno y expresivo con texturas suaves y gran iluminación.' },
    'prompt-7': { title: 'Paisaje Épico de Montañas al Atardecer', description: 'Una vista natural impresionante con nubes dramáticas y rayos dorados sobre las cimas.' },
    'prompt-8': { title: 'Oro Líquido Abstracto y Negro', description: 'Arte abstracto exclusivo y sofisticado. Perfecto como fondo para marcas de lujo y presentaciones.' },
    'prompt-9': { title: 'Interior de Lujo en Apartamento Moderno', description: 'Diseño interior de una sala elegante con muebles exclusivos e iluminación ambiental suave.' }
  },
  tr: {
    'prompt-1': { title: 'Sinematik Cyberpunk Portre', description: 'Dramatik neon ışık ve futuristik detaylarla hipergerçekçi bir portre. Karakter tasarımı ve konsept sanat için ideal.' },
    'prompt-2': { title: 'Minimalist İskandinav Villa', description: 'Doğal ışık ve temiz çizgilerle doğa içinde modern bir evin mimari görselleştirmesi.' },
    'prompt-3': { title: 'Büyülü Parlayan Fantastik Orman', description: 'Biyolüminesan bitkiler ve gizemli ışıklarla dolu büyüleyici rüya gibi bir ortam.' },
    'prompt-4': { title: 'Şık Vektör Tech Logo', description: 'Startup ve teknoloji şirketleri için modern, temiz logo tasarımı. Ölçeklenebilir ve minimalist.' },
    'prompt-5': { title: 'SaaS Dashboard UI & Web Tasarım', description: 'Web uygulamaları için profesyonel ve temiz arayüz tasarımı. Geliştiriciler için mükemmel ilham.' },
    'prompt-6': { title: 'Sevimli 3D Pixar Tarzı Karakter', description: 'Yumuşak dokular ve harika ışıkla çok sevimli, ifade dolu bir 3D karakter.' },
    'prompt-7': { title: 'Gün Batımında Epik Dağ Manzarası', description: 'Dramatik bulutlar ve zirvelere vuran altın güneş ışınlarıyla nefes kesici doğa görünümü.' },
    'prompt-8': { title: 'Soyut Sıvı Altın ve Siyah', description: 'Lüks markalar ve sunumlar için mükemmel, seçkin ve sofistike soyut sanat.' },
    'prompt-9': { title: 'Modern Dairede Lüks İç Mekan', description: 'Özel mobilyalar ve yumuşak ortam ışığıyla zarif bir oturma odası iç tasarımı.' }
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
  categoryLabel: (category: string) => string;
  promptTitle: (id: string, fallback: string, isCustom?: boolean) => string;
  promptDescription: (id: string, fallback: string, isCustom?: boolean) => string;
  tagLabel: (tag: string) => string;
  suggestedImageLabel: (name: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
const LANGUAGE_STORAGE_KEY = 'secret_prompts_language_v1';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as LanguageCode | null;
    return saved && LANGUAGES.some(item => item.code === saved) ? saved : 'en';
  });

  const setLanguage = (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
  };

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextType>(() => {
    const translate = (key: TranslationKey, values?: Record<string, string | number>) => {
      let text = extraTranslations[language][key] || translations[language][key] || extraTranslations.en[key] || translations.en[key] || key;

      if (values) {
        Object.entries(values).forEach(([name, replacement]) => {
          text = text.split(`{${name}}`).join(String(replacement));
        });
      }

      return text;
    };

    return {
      language,
      setLanguage,
      t: translate,
      categoryLabel: (category: string) => {
        const key = categoryTranslationKeys[category];
        return key ? translate(key) : category;
      },
      promptTitle: (id: string, fallback: string, isCustom?: boolean) => {
        if (isCustom) return fallback;
        return promptTranslations[language][id]?.title || promptTranslations.en[id]?.title || fallback;
      },
      promptDescription: (id: string, fallback: string, isCustom?: boolean) => {
        if (isCustom) return fallback;
        return promptTranslations[language][id]?.description || promptTranslations.en[id]?.description || fallback;
      },
      tagLabel: (tag: string) => tagTranslations[language][tag] || tagTranslations.en[tag] || tag,
      suggestedImageLabel: (name: string) => {
        const key = suggestedImageTranslationKeys[name];
        return key ? translate(key) : name;
      }
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};